name: Main Branch Guard

on:
  pull_request:
    branches:
      - main

jobs:
  validate-source:
    runs-on: ubuntu-latest

    steps:
      - name: Ensure PR comes from develop
        run: |
          echo "Source branch: ${{ github.head_ref }}"

          if [ "${{ github.head_ref }}" != "develop" ]; then
            echo "Only develop branch can merge into main."
            exit 1
          fi